development:
  clients:
    default:
      database: tabaz_development
      hosts:
        - <%= ENV.fetch('DATABASE_URL') { 'localhost:27017' } %>
      options:
        max_pool_size: 10
staging:
  clients:
    default:
      database: tabaz_staging
      hosts:
        - <%= ENV.fetch('DATABASE_URL') { 'localhost:27017' } %>
      options:
        write:
          w: 1
        raise_not_found_error: false
        max_pool_size: 10
test:
  clients:
    default:
      database: tabaz_test
      hosts:
        - <%= ENV.fetch('DATABASE_URL') { 'localhost:27017' } %>
      options:
        read:
          mode: :primary
        max_pool_size: 10
  options:
    raise_not_found_error: false
